### ISSUE TITLE
Future plans for Modals and Input Text

### ISSUE THREAD

**Issue by krittick** [Pycord-Development/pycord#1001]
### Summary

This meta issue outlines future plans to improve our implementation of modals and input text components

## `Modal`
- [ ] ~~timeout feature (not possible until discord adds support for dismissing the modal without submitting it)~~
- [x] stop() method
- [ ] decorator
- [x] wait() method (#1013)
- [x] on_error event 
- [x] `ApplicationContext` shortcut methods for sending modals
- [ ] better `_ModalWeights` class (currently just uses the same logic from `_ViewWeights`)
- [ ] better dispatching (look into removing `ModalStore` as a requirement)
- [ ] look into solving for #994
- [ ] more?

## `InputText`
- [x] decouple from `Item` inheritance
- [ ] enforce label length limits to avoid sending invalid requests to the API (in progress as part of #1065, more testing needed)
- [ ] add library-side enforcement of other limits on things like max_length etc (in progress as part of #1065, more testing needed) 
- [x] fix typing issues (e.g. label) (in progress)
- [ ] more?

## Rejected proposals:
- [ ] ~~Look at potentially moving away from Bot UI Kit (i.e. View-based approach) and treat them as higher level objects (may come as part of a larger rework to how other components are handled by the library)~~ Not in line with library goals at this time. 

Note: This issue is for organizational tracking purposes only. For discussion on any specific item, please reach out in our discord server.

**Comment by onerandomusername** [comment]
How were these issues not already fixed in any of the following pulls?
https://github.com/Pycord-Development/pycord/pull/993
https://github.com/Pycord-Development/pycord/pull/992
https://github.com/Pycord-Development/pycord/pull/988
https://github.com/Pycord-Development/pycord/pull/984
https://github.com/Pycord-Development/pycord/pull/969
https://github.com/Pycord-Development/pycord/pull/966
https://github.com/Pycord-Development/pycord/pull/630 -- initial implementation

**Comment by krittick** [comment]
It's a brand new feature that is evolving as users identify new use cases the original implementation didn't have. Most of these are new functionality additions as well, so weren't prioritized in previous PRs.

**Comment by krittick** [comment]
Closing as stale, new plans need realignment with our release schedule.
