### ISSUE TITLE
[Core] Channel Banners

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#423]
Discord has channel banners in experiment right now.

Someone could already start on implementing it.

The guild feature is added in the pr #421 

## TODO
- [ ] Implement channel banner on modify as base64 string
- [ ] Implement property banner on the channel object
- [ ] Add feature to types/guild

## Limitation
- This feature is in experiment
- Feature needs guild premium tier 3 (14 boosts)

## Ref
https://github.com/Aiko-IT-Systems/DisCatSharp/commit/274559f32c3b294bd54fef3d4a4aabfdb405e102

## Preview
![image](https://user-images.githubusercontent.com/14029133/140827190-b1a98338-962a-4ab5-b42f-11d27669d36e.png)
![image](https://user-images.githubusercontent.com/14029133/140827282-9c527d0a-39d8-49af-ae80-62585081b7ae.png)
![image](https://user-images.githubusercontent.com/14029133/140827297-aae782e0-732f-403a-a664-94ddde5cf734.png)
![2021-11-08_19h47_42](https://user-images.githubusercontent.com/14029133/140827316-0a407f3d-68f9-4dca-9f99-2d4a6be58b42.png)

**Comment by Lulalaby** [comment]
![image](https://user-images.githubusercontent.com/14029133/140827478-03f57ba5-d704-48b1-bdb9-89f693c8a6f9.png)

**Comment by Lulalaby** [comment]
CDN route for channel banners is atm:
`/banners/:channel_id/:banner_hash[.png|.jpg|.webp]`

**Comment by Lulalaby** [comment]
Channel banners endpoint is now:
` /channels/:channel_id/banners/:banner_hash[.png|.jpg|]`

**Comment by Lulalaby** [comment]
![image](https://user-images.githubusercontent.com/14029133/141372190-28523d35-4989-43d1-98e8-8e75ca126048.png)

**Comment by BobDotCom** [comment]
Channel banners were scrapped and removed by discord.
